ifdef CONFIG_TARGET_ESP8266

COMPONENT_SRCDIRS := GPIO/ESP8266
COMPONENT_ADD_INCLUDEDIRS := GPIO/ESP8266

COMPONENT_SRCDIRS += UART
COMPONENT_ADD_INCLUDEDIRS += UART




endif

ifdef CONFIG_TARGET_ESP32

COMPONENT_SRCDIRS += GPIO/ESP32
COMPONENT_ADD_INCLUDEDIRS += GPIO/ESP32

endif

COMPONENT_ADD_INCLUDEDIRS += GPIO