/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wifi_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "wifi_config.pb-c.h"
void   status_resp__init
                     (StatusResp         *message)
{
  static const StatusResp init_value = STATUS_RESP__INIT;
  *message = init_value;
}
size_t status_resp__get_packed_size
                     (const StatusResp *message)
{
  assert(message->base.descriptor == &status_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_resp__pack
                     (const StatusResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_resp__pack_to_buffer
                     (const StatusResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusResp *
       status_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusResp *)
     protobuf_c_message_unpack (&status_resp__descriptor,
                                allocator, len, data);
}
void   status_resp__free_unpacked
                     (StatusResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wifi_config_get_status_resp__init
                     (WifiConfigGetStatusResp         *message)
{
  static const WifiConfigGetStatusResp init_value = WIFI_CONFIG_GET_STATUS_RESP__INIT;
  *message = init_value;
}
size_t wifi_config_get_status_resp__get_packed_size
                     (const WifiConfigGetStatusResp *message)
{
  assert(message->base.descriptor == &wifi_config_get_status_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_config_get_status_resp__pack
                     (const WifiConfigGetStatusResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_config_get_status_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_config_get_status_resp__pack_to_buffer
                     (const WifiConfigGetStatusResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_config_get_status_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiConfigGetStatusResp *
       wifi_config_get_status_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiConfigGetStatusResp *)
     protobuf_c_message_unpack (&wifi_config_get_status_resp__descriptor,
                                allocator, len, data);
}
void   wifi_config_get_status_resp__free_unpacked
                     (WifiConfigGetStatusResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_config_get_status_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wifi_config_ap_set_info_req__init
                     (WifiConfigApSetInfoReq         *message)
{
  static const WifiConfigApSetInfoReq init_value = WIFI_CONFIG_AP_SET_INFO_REQ__INIT;
  *message = init_value;
}
size_t wifi_config_ap_set_info_req__get_packed_size
                     (const WifiConfigApSetInfoReq *message)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_config_ap_set_info_req__pack
                     (const WifiConfigApSetInfoReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_config_ap_set_info_req__pack_to_buffer
                     (const WifiConfigApSetInfoReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiConfigApSetInfoReq *
       wifi_config_ap_set_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiConfigApSetInfoReq *)
     protobuf_c_message_unpack (&wifi_config_ap_set_info_req__descriptor,
                                allocator, len, data);
}
void   wifi_config_ap_set_info_req__free_unpacked
                     (WifiConfigApSetInfoReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wifi_config_cmd_req__init
                     (WifiConfigCmdReq         *message)
{
  static const WifiConfigCmdReq init_value = WIFI_CONFIG_CMD_REQ__INIT;
  *message = init_value;
}
size_t wifi_config_cmd_req__get_packed_size
                     (const WifiConfigCmdReq *message)
{
  assert(message->base.descriptor == &wifi_config_cmd_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_config_cmd_req__pack
                     (const WifiConfigCmdReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_config_cmd_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_config_cmd_req__pack_to_buffer
                     (const WifiConfigCmdReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_config_cmd_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiConfigCmdReq *
       wifi_config_cmd_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiConfigCmdReq *)
     protobuf_c_message_unpack (&wifi_config_cmd_req__descriptor,
                                allocator, len, data);
}
void   wifi_config_cmd_req__free_unpacked
                     (WifiConfigCmdReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_config_cmd_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor status_resp__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StatusResp, status),
    &status_resp_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_resp__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange status_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor status_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatusResp",
  "StatusResp",
  "StatusResp",
  "",
  sizeof(StatusResp),
  1,
  status_resp__field_descriptors,
  status_resp__field_indices_by_name,
  1,  status_resp__number_ranges,
  (ProtobufCMessageInit) status_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wifi_config_get_status_resp__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WifiConfigGetStatusResp, status),
    &status_resp_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sta_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WifiConfigGetStatusResp, sta_status),
    &wifi_config_get_status_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_config_get_status_resp__field_indices_by_name[] = {
  1,   /* field[1] = sta_status */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange wifi_config_get_status_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wifi_config_get_status_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiConfigGetStatusResp",
  "WifiConfigGetStatusResp",
  "WifiConfigGetStatusResp",
  "",
  sizeof(WifiConfigGetStatusResp),
  2,
  wifi_config_get_status_resp__field_descriptors,
  wifi_config_get_status_resp__field_indices_by_name,
  1,  wifi_config_get_status_resp__number_ranges,
  (ProtobufCMessageInit) wifi_config_get_status_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wifi_config_ap_set_info_req__field_descriptors[2] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WifiConfigApSetInfoReq, ssid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passphrase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WifiConfigApSetInfoReq, passphrase),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_config_ap_set_info_req__field_indices_by_name[] = {
  1,   /* field[1] = passphrase */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange wifi_config_ap_set_info_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wifi_config_ap_set_info_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiConfigApSetInfoReq",
  "WifiConfigApSetInfoReq",
  "WifiConfigApSetInfoReq",
  "",
  sizeof(WifiConfigApSetInfoReq),
  2,
  wifi_config_ap_set_info_req__field_descriptors,
  wifi_config_ap_set_info_req__field_indices_by_name,
  1,  wifi_config_ap_set_info_req__number_ranges,
  (ProtobufCMessageInit) wifi_config_ap_set_info_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wifi_config_cmd_req__field_descriptors[1] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WifiConfigCmdReq, cmd),
    &wifi_config_cmd_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_config_cmd_req__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
};
static const ProtobufCIntRange wifi_config_cmd_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wifi_config_cmd_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiConfigCmdReq",
  "WifiConfigCmdReq",
  "WifiConfigCmdReq",
  "",
  sizeof(WifiConfigCmdReq),
  1,
  wifi_config_cmd_req__field_descriptors,
  wifi_config_cmd_req__field_indices_by_name,
  1,  wifi_config_cmd_req__number_ranges,
  (ProtobufCMessageInit) wifi_config_cmd_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue status_resp_type__enum_values_by_number[3] =
{
  { "StatusRespNone", "STATUS_RESP_TYPE__StatusRespNone", 0 },
  { "StatusRespFailed", "STATUS_RESP_TYPE__StatusRespFailed", 1 },
  { "StatusRespOk", "STATUS_RESP_TYPE__StatusRespOk", 2 },
};
static const ProtobufCIntRange status_resp_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex status_resp_type__enum_values_by_name[3] =
{
  { "StatusRespFailed", 1 },
  { "StatusRespNone", 0 },
  { "StatusRespOk", 2 },
};
const ProtobufCEnumDescriptor status_resp_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StatusRespType",
  "StatusRespType",
  "StatusRespType",
  "",
  3,
  status_resp_type__enum_values_by_number,
  3,
  status_resp_type__enum_values_by_name,
  1,
  status_resp_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue wifi_config_get_status_type__enum_values_by_number[5] =
{
  { "GetStatusTypeNone", "WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeNone", 0 },
  { "GetStatusTypeOffline", "WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeOffline", 1 },
  { "GetStatusTypeAssociated", "WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeAssociated", 2 },
  { "GetStatusTypeGotIP", "WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeGotIP", 3 },
  { "GetStatusTypeOnline", "WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeOnline", 4 },
};
static const ProtobufCIntRange wifi_config_get_status_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex wifi_config_get_status_type__enum_values_by_name[5] =
{
  { "GetStatusTypeAssociated", 2 },
  { "GetStatusTypeGotIP", 3 },
  { "GetStatusTypeNone", 0 },
  { "GetStatusTypeOffline", 1 },
  { "GetStatusTypeOnline", 4 },
};
const ProtobufCEnumDescriptor wifi_config_get_status_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "WifiConfigGetStatusType",
  "WifiConfigGetStatusType",
  "WifiConfigGetStatusType",
  "",
  5,
  wifi_config_get_status_type__enum_values_by_number,
  5,
  wifi_config_get_status_type__enum_values_by_name,
  1,
  wifi_config_get_status_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue wifi_config_cmd_type__enum_values_by_number[4] =
{
  { "CmdTypeNone", "WIFI_CONFIG_CMD_TYPE__CmdTypeNone", 0 },
  { "CmdTypeApplyConfig", "WIFI_CONFIG_CMD_TYPE__CmdTypeApplyConfig", 1 },
  { "CmdTypeResetConfig", "WIFI_CONFIG_CMD_TYPE__CmdTypeResetConfig", 2 },
  { "CmdTypeGetStatus", "WIFI_CONFIG_CMD_TYPE__CmdTypeGetStatus", 3 },
};
static const ProtobufCIntRange wifi_config_cmd_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex wifi_config_cmd_type__enum_values_by_name[4] =
{
  { "CmdTypeApplyConfig", 1 },
  { "CmdTypeGetStatus", 3 },
  { "CmdTypeNone", 0 },
  { "CmdTypeResetConfig", 2 },
};
const ProtobufCEnumDescriptor wifi_config_cmd_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "WifiConfigCmdType",
  "WifiConfigCmdType",
  "WifiConfigCmdType",
  "",
  4,
  wifi_config_cmd_type__enum_values_by_number,
  4,
  wifi_config_cmd_type__enum_values_by_name,
  1,
  wifi_config_cmd_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
