/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wifi_config.proto */

#ifndef PROTOBUF_C_wifi_5fconfig_2eproto__INCLUDED
#define PROTOBUF_C_wifi_5fconfig_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct StatusResp StatusResp;
typedef struct WifiConfigGetStatusResp WifiConfigGetStatusResp;
typedef struct WifiConfigApSetInfoReq WifiConfigApSetInfoReq;
typedef struct WifiConfigCmdReq WifiConfigCmdReq;


/* --- enums --- */

typedef enum _StatusRespType {
  STATUS_RESP_TYPE__StatusRespNone = 0,
  STATUS_RESP_TYPE__StatusRespFailed = 1,
  STATUS_RESP_TYPE__StatusRespOk = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STATUS_RESP_TYPE)
} StatusRespType;
typedef enum _WifiConfigGetStatusType {
  WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeNone = 0,
  WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeOffline = 1,
  WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeAssociated = 2,
  WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeGotIP = 3,
  WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeOnline = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WIFI_CONFIG_GET_STATUS_TYPE)
} WifiConfigGetStatusType;
typedef enum _WifiConfigCmdType {
  WIFI_CONFIG_CMD_TYPE__CmdTypeNone = 0,
  WIFI_CONFIG_CMD_TYPE__CmdTypeApplyConfig = 1,
  WIFI_CONFIG_CMD_TYPE__CmdTypeResetConfig = 2,
  WIFI_CONFIG_CMD_TYPE__CmdTypeGetStatus = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WIFI_CONFIG_CMD_TYPE)
} WifiConfigCmdType;

/* --- messages --- */

struct  StatusResp
{
  ProtobufCMessage base;
  StatusRespType status;
};
#define STATUS_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&status_resp__descriptor) \
    , STATUS_RESP_TYPE__StatusRespNone }


struct  WifiConfigGetStatusResp
{
  ProtobufCMessage base;
  StatusRespType status;
  WifiConfigGetStatusType sta_status;
};
#define WIFI_CONFIG_GET_STATUS_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wifi_config_get_status_resp__descriptor) \
    , STATUS_RESP_TYPE__StatusRespNone, WIFI_CONFIG_GET_STATUS_TYPE__GetStatusTypeNone }


struct  WifiConfigApSetInfoReq
{
  ProtobufCMessage base;
  char *ssid;
  char *passphrase;
};
#define WIFI_CONFIG_AP_SET_INFO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wifi_config_ap_set_info_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  WifiConfigCmdReq
{
  ProtobufCMessage base;
  WifiConfigCmdType cmd;
};
#define WIFI_CONFIG_CMD_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wifi_config_cmd_req__descriptor) \
    , WIFI_CONFIG_CMD_TYPE__CmdTypeNone }


/* StatusResp methods */
void   status_resp__init
                     (StatusResp         *message);
size_t status_resp__get_packed_size
                     (const StatusResp   *message);
size_t status_resp__pack
                     (const StatusResp   *message,
                      uint8_t             *out);
size_t status_resp__pack_to_buffer
                     (const StatusResp   *message,
                      ProtobufCBuffer     *buffer);
StatusResp *
       status_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   status_resp__free_unpacked
                     (StatusResp *message,
                      ProtobufCAllocator *allocator);
/* WifiConfigGetStatusResp methods */
void   wifi_config_get_status_resp__init
                     (WifiConfigGetStatusResp         *message);
size_t wifi_config_get_status_resp__get_packed_size
                     (const WifiConfigGetStatusResp   *message);
size_t wifi_config_get_status_resp__pack
                     (const WifiConfigGetStatusResp   *message,
                      uint8_t             *out);
size_t wifi_config_get_status_resp__pack_to_buffer
                     (const WifiConfigGetStatusResp   *message,
                      ProtobufCBuffer     *buffer);
WifiConfigGetStatusResp *
       wifi_config_get_status_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wifi_config_get_status_resp__free_unpacked
                     (WifiConfigGetStatusResp *message,
                      ProtobufCAllocator *allocator);
/* WifiConfigApSetInfoReq methods */
void   wifi_config_ap_set_info_req__init
                     (WifiConfigApSetInfoReq         *message);
size_t wifi_config_ap_set_info_req__get_packed_size
                     (const WifiConfigApSetInfoReq   *message);
size_t wifi_config_ap_set_info_req__pack
                     (const WifiConfigApSetInfoReq   *message,
                      uint8_t             *out);
size_t wifi_config_ap_set_info_req__pack_to_buffer
                     (const WifiConfigApSetInfoReq   *message,
                      ProtobufCBuffer     *buffer);
WifiConfigApSetInfoReq *
       wifi_config_ap_set_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wifi_config_ap_set_info_req__free_unpacked
                     (WifiConfigApSetInfoReq *message,
                      ProtobufCAllocator *allocator);
/* WifiConfigCmdReq methods */
void   wifi_config_cmd_req__init
                     (WifiConfigCmdReq         *message);
size_t wifi_config_cmd_req__get_packed_size
                     (const WifiConfigCmdReq   *message);
size_t wifi_config_cmd_req__pack
                     (const WifiConfigCmdReq   *message,
                      uint8_t             *out);
size_t wifi_config_cmd_req__pack_to_buffer
                     (const WifiConfigCmdReq   *message,
                      ProtobufCBuffer     *buffer);
WifiConfigCmdReq *
       wifi_config_cmd_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wifi_config_cmd_req__free_unpacked
                     (WifiConfigCmdReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StatusResp_Closure)
                 (const StatusResp *message,
                  void *closure_data);
typedef void (*WifiConfigGetStatusResp_Closure)
                 (const WifiConfigGetStatusResp *message,
                  void *closure_data);
typedef void (*WifiConfigApSetInfoReq_Closure)
                 (const WifiConfigApSetInfoReq *message,
                  void *closure_data);
typedef void (*WifiConfigCmdReq_Closure)
                 (const WifiConfigCmdReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    status_resp_type__descriptor;
extern const ProtobufCEnumDescriptor    wifi_config_get_status_type__descriptor;
extern const ProtobufCEnumDescriptor    wifi_config_cmd_type__descriptor;
extern const ProtobufCMessageDescriptor status_resp__descriptor;
extern const ProtobufCMessageDescriptor wifi_config_get_status_resp__descriptor;
extern const ProtobufCMessageDescriptor wifi_config_ap_set_info_req__descriptor;
extern const ProtobufCMessageDescriptor wifi_config_cmd_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_wifi_5fconfig_2eproto__INCLUDED */
