# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_presentation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_presentation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x64\x61ta_presentation.proto\"4\n\x13ProtoBufferLedState\x12\x1d\n\tled_state\x18\x01 \x01(\x0e\x32\n.LedStates*F\n\tLedStates\x12\x14\n\x10LED_STATE_UNKOWN\x10\x00\x12\x11\n\rLED_STATE_OFF\x10\x01\x12\x10\n\x0cLED_STATE_ON\x10\x02\x62\x06proto3')
)

_LEDSTATES = _descriptor.EnumDescriptor(
  name='LedStates',
  full_name='LedStates',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LED_STATE_UNKOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LED_STATE_OFF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LED_STATE_ON', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=81,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_LEDSTATES)

LedStates = enum_type_wrapper.EnumTypeWrapper(_LEDSTATES)
LED_STATE_UNKOWN = 0
LED_STATE_OFF = 1
LED_STATE_ON = 2



_PROTOBUFFERLEDSTATE = _descriptor.Descriptor(
  name='ProtoBufferLedState',
  full_name='ProtoBufferLedState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='led_state', full_name='ProtoBufferLedState.led_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=79,
)

_PROTOBUFFERLEDSTATE.fields_by_name['led_state'].enum_type = _LEDSTATES
DESCRIPTOR.message_types_by_name['ProtoBufferLedState'] = _PROTOBUFFERLEDSTATE
DESCRIPTOR.enum_types_by_name['LedStates'] = _LEDSTATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoBufferLedState = _reflection.GeneratedProtocolMessageType('ProtoBufferLedState', (_message.Message,), dict(
  DESCRIPTOR = _PROTOBUFFERLEDSTATE,
  __module__ = 'data_presentation_pb2'
  # @@protoc_insertion_point(class_scope:ProtoBufferLedState)
  ))
_sym_db.RegisterMessage(ProtoBufferLedState)


# @@protoc_insertion_point(module_scope)
