/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wifi_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "wifi_config.pb-c.h"
void   wifi_config_ap_set_info_req__init
                     (WifiConfigApSetInfoReq         *message)
{
  static const WifiConfigApSetInfoReq init_value = WIFI_CONFIG_AP_SET_INFO_REQ__INIT;
  *message = init_value;
}
size_t wifi_config_ap_set_info_req__get_packed_size
                     (const WifiConfigApSetInfoReq *message)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_config_ap_set_info_req__pack
                     (const WifiConfigApSetInfoReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_config_ap_set_info_req__pack_to_buffer
                     (const WifiConfigApSetInfoReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiConfigApSetInfoReq *
       wifi_config_ap_set_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiConfigApSetInfoReq *)
     protobuf_c_message_unpack (&wifi_config_ap_set_info_req__descriptor,
                                allocator, len, data);
}
void   wifi_config_ap_set_info_req__free_unpacked
                     (WifiConfigApSetInfoReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_config_ap_set_info_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wifi_config_ap_set_info_req__field_descriptors[2] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WifiConfigApSetInfoReq, ssid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passphrase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WifiConfigApSetInfoReq, passphrase),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_config_ap_set_info_req__field_indices_by_name[] = {
  1,   /* field[1] = passphrase */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange wifi_config_ap_set_info_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wifi_config_ap_set_info_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiConfigApSetInfoReq",
  "WifiConfigApSetInfoReq",
  "WifiConfigApSetInfoReq",
  "",
  sizeof(WifiConfigApSetInfoReq),
  2,
  wifi_config_ap_set_info_req__field_descriptors,
  wifi_config_ap_set_info_req__field_indices_by_name,
  1,  wifi_config_ap_set_info_req__number_ranges,
  (ProtobufCMessageInit) wifi_config_ap_set_info_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
