COMPONENT_SRCDIRS := .
COMPONENT_SRCDIRS += Protobuffer
COMPONENT_SRCDIRS += Protobuffer/Protobuf-c

COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_INCLUDEDIRS += Protobuffer
COMPONENT_ADD_INCLUDEDIRS += Protobuffer/Protobuf-c