COMPONENT_SRCDIRS := WIFI
COMPONENT_SRCDIRS += WIFI_AP
COMPONENT_SRCDIRS += WIFI_STA
COMPONENT_SRCDIRS += WIFI_Config
COMPONENT_SRCDIRS += WIFI_Config/Protobuf

COMPONENT_ADD_INCLUDEDIRS := WIFI
COMPONENT_ADD_INCLUDEDIRS += WIFI_AP
COMPONENT_ADD_INCLUDEDIRS += WIFI_STA
COMPONENT_ADD_INCLUDEDIRS += WIFI_Config
COMPONENT_ADD_INCLUDEDIRS += WIFI_Config/Protobuf

CFLAGS += -DCONFIG_WIFI_COMPONENT_STACK_SIZE=$(CONFIG_WIFI_COMPONENT_STACK_SIZE) \
				-DCONFIG_WIFI_COMPONENT_TSK_PRI=$(CONFIG_WIFI_COMPONENT_TSK_PRI) \
				-DCONFIG_WIFI_AP_SSID_MAX_LENGTH=$(CONFIG_WIFI_AP_SSID_MAX_LENGTH) \
				-DCONFIG_WIFI_AP_MAX_PASSPHRASE_LENGTH=$(CONFIG_WIFI_AP_MAX_PASSPHRASE_LENGTH)

ifdef CONFIG_WIFI_AP_SSID_HIDDEN
CFLAGS += -DCONFIG_WIFI_AP_SSID_HIDDEN='1'
else
CFLAGS += -DCONFIG_WIFI_AP_SSID_HIDDEN='0'
endif

ifdef CONFIG_WIFI_AP_NAME_AUTOGEN
CFLAGS += -DCONFIG_WIFI_AP_NAME_AUTOGEN='1'
else
CFLAGS += -DCONFIG_WIFI_AP_NAME_AUTOGEN='0'
endif

ifdef CONFIG_WIFI_AP_PASSPHRASE_AUTOGEN
CFLAGS += -DCONFIG_WIFI_AP_PASSPHRASE_AUTOGEN='1'
else
CFLAGS += -DCONFIG_WIFI_AP_PASSPHRASE_AUTOGEN='0'
endif

ifdef CONFIG_WIFI_COMPONENT_LOGE_ENABLED
CFLAGS += -DCONFIG_WIFI_COMPONENT_LOGE_ENABLED='1'
else
CFLAGS += -DCONFIG_WIFI_COMPONENT_LOGE_ENABLED='0'
endif