COMPONENT_SRCDIRS := WIFI
COMPONENT_SRCDIRS += WIFI_AP
COMPONENT_SRCDIRS += WIFI_STA
COMPONENT_SRCDIRS += WIFI_Prov
COMPONENT_SRCDIRS += WIFI_Prov/Protobuf
COMPONENT_SRCDIRS += WIFI_Param

COMPONENT_ADD_INCLUDEDIRS := WIFI
COMPONENT_ADD_INCLUDEDIRS += WIFI_AP
COMPONENT_ADD_INCLUDEDIRS += WIFI_STA
COMPONENT_ADD_INCLUDEDIRS += WIFI_Prov
COMPONENT_ADD_INCLUDEDIRS += WIFI_Prov/Protobuf
COMPONENT_ADD_INCLUDEDIRS += WIFI_Param